"""Add notification system tables

Revision ID: e65cd20c446e
Revises: 0001_create_all_tables
Create Date: 2025-10-15 02:12:55.019445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65cd20c446e'
down_revision = '0001_create_all_tables'  # Changed from 0035338f4b2f to 0001
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('preference_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('notification_type', sa.Enum('ASSIGNMENT_CREATED', 'ASSIGNMENT_GRADED', 'ASSIGNMENT_DUE_SOON', 'COURSE_UPDATE', 'GRADE_POSTED', 'ATTENDANCE_MARKED', 'ATTENDANCE_WARNING', 'ABSENCE_REPORTED', 'PAYMENT_DUE', 'PAYMENT_RECEIVED', 'PAYMENT_OVERDUE', 'PAYMENT_REMINDER', 'ENROLLMENT_APPROVED', 'ENROLLMENT_REJECTED', 'COURSE_FULL', 'WAITLIST_AVAILABLE', 'ANNOUNCEMENT', 'MESSAGE_RECEIVED', 'CHAT_MENTION', 'EVENT_REMINDER', 'CLASS_CANCELLED', 'SCHEDULE_CHANGE', 'ACCOUNT_CREATED', 'PASSWORD_RESET', 'PROFILE_UPDATED', 'SYSTEM_MAINTENANCE', 'NEW_ENROLLMENT', 'PAYMENT_PENDING', 'LOW_ATTENDANCE_ALERT', name='notificationtype'), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('digest_mode', sa.Boolean(), nullable=True),
    sa.Column('digest_frequency', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('preference_id')
    )
    op.create_index(op.f('ix_notification_preferences_preference_id'), 'notification_preferences', ['preference_id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('notification_templates',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('ASSIGNMENT_CREATED', 'ASSIGNMENT_GRADED', 'ASSIGNMENT_DUE_SOON', 'COURSE_UPDATE', 'GRADE_POSTED', 'ATTENDANCE_MARKED', 'ATTENDANCE_WARNING', 'ABSENCE_REPORTED', 'PAYMENT_DUE', 'PAYMENT_RECEIVED', 'PAYMENT_OVERDUE', 'PAYMENT_REMINDER', 'ENROLLMENT_APPROVED', 'ENROLLMENT_REJECTED', 'COURSE_FULL', 'WAITLIST_AVAILABLE', 'ANNOUNCEMENT', 'MESSAGE_RECEIVED', 'CHAT_MENTION', 'EVENT_REMINDER', 'CLASS_CANCELLED', 'SCHEDULE_CHANGE', 'ACCOUNT_CREATED', 'PASSWORD_RESET', 'PROFILE_UPDATED', 'SYSTEM_MAINTENANCE', 'NEW_ENROLLMENT', 'PAYMENT_PENDING', 'LOW_ATTENDANCE_ALERT', name='notificationtype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('title_template', sa.String(length=200), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('email_subject_template', sa.String(length=200), nullable=True),
    sa.Column('email_body_template', sa.Text(), nullable=True),
    sa.Column('sms_template', sa.String(length=160), nullable=True),
    sa.Column('default_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notificationpriority'), nullable=True),
    sa.Column('default_channels', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('template_id'),
    sa.UniqueConstraint('notification_type')
    )
    op.create_index(op.f('ix_notification_templates_template_id'), 'notification_templates', ['template_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('notification_type', sa.Enum('ASSIGNMENT_CREATED', 'ASSIGNMENT_GRADED', 'ASSIGNMENT_DUE_SOON', 'COURSE_UPDATE', 'GRADE_POSTED', 'ATTENDANCE_MARKED', 'ATTENDANCE_WARNING', 'ABSENCE_REPORTED', 'PAYMENT_DUE', 'PAYMENT_RECEIVED', 'PAYMENT_OVERDUE', 'PAYMENT_REMINDER', 'ENROLLMENT_APPROVED', 'ENROLLMENT_REJECTED', 'COURSE_FULL', 'WAITLIST_AVAILABLE', 'ANNOUNCEMENT', 'MESSAGE_RECEIVED', 'CHAT_MENTION', 'EVENT_REMINDER', 'CLASS_CANCELLED', 'SCHEDULE_CHANGE', 'ACCOUNT_CREATED', 'PASSWORD_RESET', 'PROFILE_UPDATED', 'SYSTEM_MAINTENANCE', 'NEW_ENROLLMENT', 'PAYMENT_PENDING', 'LOW_ATTENDANCE_ALERT', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notificationpriority'), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('action_text', sa.String(length=100), nullable=True),
    sa.Column('related_course_id', sa.Integer(), nullable=True),
    sa.Column('related_assignment_id', sa.Integer(), nullable=True),
    sa.Column('related_enrollment_id', sa.Integer(), nullable=True),
    sa.Column('related_payment_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('sent_via', sa.String(length=50), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('sms_sent', sa.Boolean(), nullable=True),
    sa.Column('sms_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'SMS', 'PUSH', name='notificationchannel'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_notification_logs_log_id'), 'notification_logs', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_logs_log_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_templates_template_id'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_preference_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
